export const clientes = {
  name: "clientes",
  query: `
    PRAGMA journal_mode = 'wal';
    CREATE TABLE IF NOT EXISTS clientes (
      cd_entidade INTEGER PRIMARY KEY,
      ds_entidade TEXT,
      ds_nomefantasia TEXT,
      nr_cpfcnpj TEXT,
      nr_rg TEXT,
      nr_inscmunicipal TEXT,
      nr_ie TEXT,
      cd_regiao INTEGER,
      cd_vendedor INTEGER,
      nr_telefone TEXT,
      nr_celular TEXT,
      cd_cidade INTEGER,
      ds_cidade TEXT,
      cd_estado INTEGER,
      ds_uf TEXT,
      ds_endereco TEXT,
      ds_enderecoent TEXT,
      nr_numero INTEGER,
      nr_numeroent INTEGER,
      ds_letra TEXT,
      ds_letraent TEXT,
      ds_complemento TEXT,
      ds_complementoent TEXT,
      cd_forma_pagamento INTEGER,
      cd_frete INTEGER,
      ds_bairro TEXT,
      ds_bairroent TEXT,
      nr_cep TEXT,
      nr_cepent TEXT,
      nr_caixapostalent TEXT,
      ds_email TEXT,
      ds_observacoes TEXT,
      ds_observacoes_fin TEXT,
      dt_nascimento TEXT,
      x_prospecto BOOLEAN,
      cd_tabelapreco INTEGER,
      cd_regtributario INTEGER,
      cd_carteira INTEGER,
      x_contribuinte BOOLEAN,
      x_trr BOOLEAN,
      cd_cidadeent INTEGER,
      cd_cidadecob INTEGER,
      nr_latitude REAL,
      nr_longitude REAL,
      x_bloqfaturamento BOOLEAN,
      cd_usuario INTEGER,
      cd_usuarioat INTEGER
    );
  `,
};
